package io.github.rolfdobbelaere.ledart;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

import static io.github.rolfdobbelaere.ledart.GoogleColors.*;

/**
 * Dev Runner: World Tour. The Nano Banana developer (sprite sheet generated by Nano Banana 2 from the
 * nano-developer image) runs through Jungle, Beach, City, BouncyLand and Grass, back into the Jungle, in one
 * continuous seamless loop. See {@code storyboards/dev-runner-world-tour.md}.
 *
 * <p>Units: game logic in LED pixels (64 wide), drawing in a 128x128 buffer. The camera scrolls 960 LED pixels in
 * 24 s. Every layer is periodic in its own scroll distance and every time-based animation completes whole cycles in
 * 24 s, so the last frame flows into the first. Themes are regions of the world: each layer decides its theme from its
 * own world coordinate, so far scenery of the next theme arrives first and the ground changes under the runner's feet.
 */
final class DevRunnerWorldTour {

    static final int FPS = 25;
    static final double DURATION = 24.0;
    static final int FRAME_COUNT = (int) Math.round(DURATION * FPS);
    static final int DELAY_MS = 1000 / FPS;

    private static final int W = 128;
    private static final double SPEED = 40, LOOP = 960, SEG = 192;
    private static final double DEV_X = 20, GROUND = 52;           // LED pixels
    private static final int JUNGLE = 0, BEACH = 1, CITY = 2, BOUNCY = 3, GRASS = 4;
    private static final double TAU = Math.PI * 2;

    // ------------------------------------------------------------------ helpers

    private static double clamp01(double v) { return Math.clamp(v, 0, 1); }
    private static double smooth(double t) { t = clamp01(t); return t * t * (3 - 2 * t); }
    private static double smoothstep(double a, double b, double x) { return smooth((x - a) / (b - a)); }
    private static double fmod(double a, double m) { return ((a % m) + m) % m; }

    private static double hash(long a, long b) {
        long h = a * 374761393L + b * 668265263L + 1442695040888963407L;
        h = (h ^ (h >>> 13)) * 1274126177L;
        return ((h ^ (h >>> 16)) & 0xFFFFFF) / (double) 0x1000000;
    }

    private static int theme(double worldX) {
        return (int) Math.floorMod((long) Math.floor(worldX / SEG), 5L);
    }

    /** Theme at a world position with a soft zone around region borders: {themeA, themeB, mix}. */
    private static double[] themeBlend(double worldX, double half) {
        double local = fmod(worldX, SEG);
        int here = theme(worldX);
        if (local < half) return new double[]{(here + 4) % 5, here, smoothstep(-half, half, local)};
        if (local > SEG - half) return new double[]{here, (here + 1) % 5, smoothstep(-half, half, local - SEG)};
        return new double[]{here, here, 0};
    }

    /**
     * World position a parallax layer element "belongs" to: chosen so the element in the middle of the screen shows
     * the same region the camera is over. Elements of the next region therefore enter from the right edge and reach
     * the middle exactly when the runner does.
     */
    private static double layerWorld(double u, double f) {
        return (u - 32) / f + 32;
    }

    /** Seamlessly periodic noise along u (period P) by walking a circle in noise space. */
    private static double loopNoise(double u, double period, double y, double scale, double seed) {
        double a = TAU * u / period, r = period / TAU * scale;
        return Noise.fbm(Math.cos(a) * r + seed, Math.sin(a) * r, y * scale + seed * 0.37, 4);
    }

    /** A sine that completes n whole cycles per loop, so it is seamless. */
    private static double wave(double t, int n, double phase) {
        return Math.sin(TAU * n * t / DURATION + phase);
    }

    // ------------------------------------------------------------------ hi-res canvas

    private static final class Buf {
        final double[] r = new double[W * W], g = new double[W * W], b = new double[W * W];

        void over(int x, int y, int c, double a) {
            if (x < 0 || y < 0 || x >= W || y >= W || a <= 0) return;
            int i = y * W + x;
            a = Math.min(1, a);
            r[i] += (GoogleColors.r(c) - r[i]) * a;
            g[i] += (GoogleColors.g(c) - g[i]) * a;
            b[i] += (GoogleColors.b(c) - b[i]) * a;
        }

        void add(int x, int y, int c, double a) {
            if (x < 0 || y < 0 || x >= W || y >= W || a <= 0) return;
            int i = y * W + x;
            r[i] += GoogleColors.r(c) * a;
            g[i] += GoogleColors.g(c) * a;
            b[i] += GoogleColors.b(c) * a;
        }

        /** Anti-aliased filled disc, hi-res coordinates. */
        void disc(double cx, double cy, double rad, int c, double a) {
            for (int y = (int) Math.floor(cy - rad - 1); y <= cy + rad + 1; y++) {
                for (int x = (int) Math.floor(cx - rad - 1); x <= cx + rad + 1; x++) {
                    double d = Math.hypot(x + 0.5 - cx, y + 0.5 - cy);
                    over(x, y, c, a * clamp01(rad + 0.5 - d));
                }
            }
        }

        void ellipse(double cx, double cy, double rx, double ry, int c, double a) {
            for (int y = (int) Math.floor(cy - ry - 1); y <= cy + ry + 1; y++) {
                for (int x = (int) Math.floor(cx - rx - 1); x <= cx + rx + 1; x++) {
                    double dx = (x + 0.5 - cx) / rx, dy = (y + 0.5 - cy) / ry;
                    double d = (Math.sqrt(dx * dx + dy * dy) - 1) * Math.min(rx, ry);
                    over(x, y, c, a * clamp01(0.5 - d));
                }
            }
        }

        void rect(double x0, double y0, double x1, double y1, int c, double a) {
            for (int y = (int) Math.floor(y0); y < Math.ceil(y1); y++) {
                for (int x = (int) Math.floor(x0); x < Math.ceil(x1); x++) {
                    double cov = clamp01(Math.min(x + 1, x1) - Math.max(x, x0)) * clamp01(Math.min(y + 1, y1) - Math.max(y, y0));
                    over(x, y, c, a * cov);
                }
            }
        }

        /** Thick anti-aliased line segment. */
        void line(double x0, double y0, double x1, double y1, double w, int c, double a) {
            int minX = (int) Math.floor(Math.min(x0, x1) - w - 1), maxX = (int) Math.ceil(Math.max(x0, x1) + w + 1);
            int minY = (int) Math.floor(Math.min(y0, y1) - w - 1), maxY = (int) Math.ceil(Math.max(y0, y1) + w + 1);
            double dx = x1 - x0, dy = y1 - y0, len2 = Math.max(1e-6, dx * dx + dy * dy);
            for (int y = minY; y <= maxY; y++) {
                for (int x = minX; x <= maxX; x++) {
                    double px = x + 0.5 - x0, py = y + 0.5 - y0;
                    double h = clamp01((px * dx + py * dy) / len2);
                    double d = Math.hypot(px - dx * h, py - dy * h);
                    over(x, y, c, a * clamp01(w / 2 + 0.5 - d));
                }
            }
        }

        void glow(double cx, double cy, double rad, int c, double a) {
            int reach = (int) Math.ceil(rad * 2.2);
            for (int y = (int) cy - reach; y <= cy + reach; y++) {
                for (int x = (int) cx - reach; x <= cx + reach; x++) {
                    double d = Math.hypot(x + 0.5 - cx, y + 0.5 - cy);
                    add(x, y, c, a * Math.exp(-d * d / (rad * rad)));
                }
            }
        }

        Canvas toCanvas() {
            Canvas c = new Canvas();
            for (int y = 0; y < 64; y++) {
                for (int x = 0; x < 64; x++) {
                    int i = y * 2 * W + x * 2;
                    double rr = (r[i] + r[i + 1] + r[i + W] + r[i + W + 1]) / 4;
                    double gg = (g[i] + g[i + 1] + g[i + W] + g[i + W + 1]) / 4;
                    double bb = (b[i] + b[i + 1] + b[i + W] + b[i + W + 1]) / 4;
                    c.set(x, y, (to8(rr) << 16) | (to8(gg) << 8) | to8(bb));
                }
            }
            return c;
        }

        private static int to8(double v) { return (int) Math.clamp(Math.round(v), 0, 255); }
    }

    // ------------------------------------------------------------------ the Nano Banana sprite sheet

    /** One pose: ARGB pixels at hi-res scale, with the head's x centre and the feet at the bottom row. */
    private record Pose(int w, int h, int[] argb, double headX) {}

    private static final List<Pose> POSES = loadPoses(Path.of("assets/nano-developer-runsheet_v1.png"), 44);

    private static boolean isBackground(int rgb) {
        int r = (rgb >> 16) & 0xFF, g = (rgb >> 8) & 0xFF, b = rgb & 0xFF;
        return (g > 140 && g > r * 1.35 && g > b * 1.35) || (g > r + 28 && g > b + 14 && r < 130); // key + shadow
    }

    private static List<Pose> loadPoses(Path sheet, int targetHeight) {
        BufferedImage img;
        try {
            img = ImageIO.read(sheet.toFile());
        } catch (IOException e) {
            throw new UncheckedIOException("Missing sprite sheet " + sheet + " (generate it with the 'sprites' command)", e);
        }
        int w = img.getWidth(), h = img.getHeight();
        // Split into frames by empty columns.
        boolean[] used = new boolean[w];
        for (int x = 0; x < w; x++) {
            int count = 0;
            for (int y = 0; y < h; y++) if (!isBackground(img.getRGB(x, y))) count++;
            used[x] = count > 2;
        }
        List<int[]> spans = new ArrayList<>();
        for (int x = 0; x < w; x++) {
            if (!used[x]) continue;
            int start = x;
            while (x < w && used[x]) x++;
            if (!spans.isEmpty() && start - spans.getLast()[1] < 10) spans.getLast()[1] = x;   // merge tiny gaps
            else spans.add(new int[]{start, x});
        }
        spans.removeIf(s -> s[1] - s[0] < w / 40);
        // Bounding boxes and a common scale from the running frames.
        List<int[]> boxes = new ArrayList<>();
        for (int[] s : spans) {
            int top = h, bottom = 0;
            for (int x = s[0]; x < s[1]; x++) {
                for (int y = 0; y < h; y++) {
                    if (!isBackground(img.getRGB(x, y))) { top = Math.min(top, y); bottom = Math.max(bottom, y); }
                }
            }
            boxes.add(new int[]{s[0], top, s[1], bottom + 1});
        }
        double runHeight = boxes.stream().limit(4).mapToInt(bx -> bx[3] - bx[1]).sorted().skip(1).findFirst().orElse(400);
        double scale = targetHeight / runHeight;

        List<Pose> poses = new ArrayList<>();
        for (int[] bx : boxes) {
            int tw = Math.max(1, (int) Math.round((bx[2] - bx[0]) * scale)), th = Math.max(1, (int) Math.round((bx[3] - bx[1]) * scale));
            int[] out = new int[tw * th];
            double headSum = 0, headCount = 0;
            for (int ty = 0; ty < th; ty++) {
                for (int tx = 0; tx < tw; tx++) {
                    int sx0 = bx[0] + (int) (tx / scale), sx1 = Math.max(sx0 + 1, bx[0] + (int) ((tx + 1) / scale));
                    int sy0 = bx[1] + (int) (ty / scale), sy1 = Math.max(sy0 + 1, bx[1] + (int) ((ty + 1) / scale));
                    double r = 0, g = 0, b = 0, a = 0, n = 0;
                    for (int sy = sy0; sy < Math.min(sy1, h); sy++) {
                        for (int sx = sx0; sx < Math.min(sx1, w); sx++) {
                            int c = img.getRGB(sx, sy);
                            n++;
                            if (isBackground(c)) continue;
                            int cr = (c >> 16) & 0xFF, cg = (c >> 8) & 0xFF, cb = c & 0xFF;
                            cg = Math.min(cg, Math.max(cr, cb) + 20);                  // remove green spill on edges
                            r += cr; g += cg; b += cb; a++;
                        }
                    }
                    double alpha = n == 0 ? 0 : smoothstep(0.3, 0.7, a / n);
                    if (alpha <= 0) continue;
                    int col = ((int) (r / a) << 16) | ((int) (g / a) << 8) | (int) (b / a);
                    out[ty * tw + tx] = ((int) Math.round(alpha * 255) << 24) | col;
                    if (ty < th * 0.35) { headSum += tx; headCount++; }
                }
            }
            poses.add(new Pose(tw, th, out, headCount > 0 ? headSum / headCount : tw / 2.0));
        }
        return poses;
    }

    private static void drawPose(Buf buf, Pose p, double headX, double feetY) {
        int x0 = (int) Math.round(headX - p.headX()), y0 = (int) Math.round(feetY - p.h());
        for (int y = 0; y < p.h(); y++) {
            for (int x = 0; x < p.w(); x++) {
                int c = p.argb()[y * p.w() + x];
                int a = c >>> 24;
                if (a > 0) buf.over(x0 + x, y0 + y, c & 0xFFFFFF, a / 255.0);
            }
        }
    }

    // ------------------------------------------------------------------ gameplay (world x within a 960 loop)

    private record Arc(double x0, double x1, double h0, double h1, double apex, boolean ground0, boolean ground1) {}

    private record Thing(double x, int kind, int theme) {}

    private static final int BUG = 0, COIN = 1, LOG = 2, CASTLE = 3, CONE = 4, HYDRANT = 5, ROCK = 6, TRAMPOLINE = 7;

    private static final List<Arc> ARCS = new ArrayList<>();
    private static final List<Thing> THINGS = new ArrayList<>();

    static {
        for (int s = 0; s < 5; s++) {
            double o = s * SEG;
            switch (s) {
                case JUNGLE -> {
                    stomp(o, 40, 64, 112, 16, s);
                    THINGS.add(new Thing(o + 88, COIN, s));
                    hop(o, 134, 150, 168, 12, LOG, s);
                }
                case BEACH -> {
                    hop(o, 34, 52, 70, 13, CASTLE, s);
                    stomp(o, 92, 112, 150, 14, s);
                    THINGS.add(new Thing(o + 131, COIN, s));
                }
                case CITY -> {
                    hop(o, 26, 40, 54, 11, CONE, s);
                    stomp(o, 80, 100, 140, 15, s);
                    THINGS.add(new Thing(o + 120, COIN, s));
                    hop(o, 150, 165, 180, 12, HYDRANT, s);
                }
                case BOUNCY -> {
                    THINGS.add(new Thing(o + 36, TRAMPOLINE, s));
                    ARCS.add(new Arc(o + 36, o + 96, 0, 0, 28, true, true));
                    THINGS.add(new Thing(o + 66, COIN, s));
                    THINGS.add(new Thing(o + 112, TRAMPOLINE, s));
                    ARCS.add(new Arc(o + 112, o + 172, 0, 0, 24, true, true));
                    THINGS.add(new Thing(o + 142, COIN, s));
                }
                default -> {
                    stomp(o, 40, 60, 100, 15, s);
                    THINGS.add(new Thing(o + 80, COIN, s));
                    hop(o, 134, 150, 166, 12, ROCK, s);
                }
            }
        }
    }

    private static void stomp(double o, double from, double bug, double to, double bounce, int theme) {
        ARCS.add(new Arc(o + from, o + bug, 0, 6, 10, true, false));
        ARCS.add(new Arc(o + bug, o + to, 6, 0, bounce, false, true));
        THINGS.add(new Thing(o + bug, BUG, theme));
    }

    private static void hop(double o, double from, double at, double to, double h, int kind, int theme) {
        ARCS.add(new Arc(o + from, o + to, 0, 0, h, true, true));
        THINGS.add(new Thing(o + at, kind, theme));
    }

    private static Arc arcAt(double wx) {
        for (Arc a : ARCS) if (wx >= a.x0() && wx < a.x1()) return a;
        return null;
    }

    private static double heightAt(double wx) {
        Arc a = arcAt(wx);
        if (a == null) return 0;
        double u = (wx - a.x0()) / (a.x1() - a.x0());
        return a.h0() + (a.h1() - a.h0()) * u + 4 * a.apex() * u * (1 - u);
    }

    /** Signed distance (world x) from the runner to a thing, wrapped to [-480, 480). */
    private static double rel(double thingX, double devWx) {
        return fmod(thingX - devWx + LOOP / 2, LOOP) - LOOP / 2;
    }

    // ------------------------------------------------------------------ frame

    static Canvas frame(int index) {
        return render(index / (double) FPS);
    }

    static Canvas render(double t) {
        double camX = SPEED * t;                         // LED px, wraps every LOOP
        Buf buf = new Buf();
        sky(buf, t, camX);
        farLayer(buf, t, camX);
        midLayer(buf, t, camX);
        nearLayer(buf, t, camX);
        ground(buf, t, camX);
        double devWx = fmod(camX + DEV_X, LOOP);
        things(buf, t, camX, devWx);
        runner(buf, devWx);
        effects(buf, t, camX, devWx);
        companion(buf, t);
        foreground(buf, t, camX);
        return buf.toCanvas();
    }

    // ------------------------------------------------------------------ sky

    private static final int[][] SKY = {
            {0x0A3346, 0x9EE6C4},   // jungle: deep teal above, misty light below
            {0x1565C0, 0xBFEFFF},   // beach
            {0x1A1446, 0xFF8A65},   // city sunset
            {0x9C6BFF, 0xFFD6F2},   // bouncyland pastel
            {0x3D8BFD, 0xDDF4FF}};  // grass: clear day

    private static void sky(Buf buf, double t, double camX) {
        double[] tb = themeBlend(camX + 32, 70);
        int a = (int) tb[0], b = (int) tb[1];
        double m = tb[2];
        for (int y = 0; y < 104; y++) {
            double v = clamp01(y / 92.0);
            int top = lerp(SKY[a][0], SKY[b][0], m), bottom = lerp(SKY[a][1], SKY[b][1], m);
            int col = lerp(top, bottom, v);
            for (int x = 0; x < W; x++) buf.over(x, y, col, 1);
        }
        for (int k = 0; k < 2; k++) {
            int th = k == 0 ? a : b;
            double wgt = k == 0 ? 1 - m : m;
            if (wgt <= 0.001 || (k == 1 && a == b)) continue;
            skyDecor(buf, t, th, wgt);
        }
        // Soft clouds, tinted by the sky.
        int tint = lerp(SKY[a][1], SKY[b][1], m);
        double cloudAmount = 1 - 0.5 * (tb[0] == CITY ? 1 - m : 0) - 0.5 * (tb[1] == CITY ? m : 0);
        for (int y = 0; y < 70; y++) {
            for (int x = 0; x < W; x++) {
                double u = x / 2.0 + camX * 0.15;
                double n = loopNoise(u, LOOP * 0.15, y / 2.0, 0.09, 3);
                double c = smoothstep(0.15, 0.6, n) * (1 - y / 75.0) * 0.75 * cloudAmount;
                buf.over(x, y, lerp(0xFFFFFF, tint, 0.35), c);
            }
        }
    }

    private static void skyDecor(Buf buf, double t, int theme, double w) {
        switch (theme) {
            case JUNGLE -> {                                                     // light shafts through the canopy
                for (int y = 0; y < 104; y++) {
                    for (int x = 0; x < W; x++) {
                        double s = fmod(x * 0.6 + y + wave(t, 2, 0) * 6, 44);
                        if (s < 12) buf.add(x, y, 0xFFF3B0, w * 0.07 * (1 - y / 110.0) * Math.sin(Math.PI * s / 12));
                    }
                }
            }
            case BEACH -> { buf.glow(96, 24, 18, 0xFFE082, 0.5 * w); buf.disc(96, 24, 10, 0xFFF59D, w); }
            case CITY -> {                                                       // big retro sunset sun behind the skyline
                buf.glow(76, 66, 26, 0xFF7043, 0.45 * w);
                for (int y = 46; y < 86; y++) {
                    for (int x = 56; x < 97; x++) {
                        double d = Math.hypot(x + 0.5 - 76, y + 0.5 - 66);
                        boolean stripe = y > 66 && ((y - 66) % 6) < 2;
                        if (d < 18 && !stripe) buf.over(x, y, lerp(0xFFD54F, 0xFF5252, (y - 48) / 36.0), w * clamp01(18.5 - d));
                    }
                }
            }
            case BOUNCY -> {                                                     // rainbow arc
                int[] bands = {RED, 0xFF9800, YELLOW, GREEN, BLUE, 0x9177C7};
                for (int y = 0; y < 104; y++) {
                    for (int x = 0; x < W; x++) {
                        double d = Math.hypot(x + 0.5 - 64, y + 0.5 - 104);
                        int band = (int) ((d - 56) / 4);
                        if (band >= 0 && band < bands.length) buf.over(x, y, bands[bands.length - 1 - band], 0.55 * w);
                    }
                }
            }
            default -> { buf.glow(24, 20, 14, 0xFFF59D, 0.45 * w); buf.disc(24, 20, 8, 0xFFFDE7, w); }
        }
    }

    // ------------------------------------------------------------------ far layer (factor 0.2): horizon silhouettes

    private static double farHeight(int theme, double u) {
        double p = 192;
        return switch (theme) {
            case JUNGLE -> 31 + 5 * Math.sin(TAU * 2 * u / p) + 3 * Math.sin(TAU * 5 * u / p + 1) + 1.5 * Math.sin(TAU * 11 * u / p);
            case BEACH -> 42 - Math.max(0, 4 - Math.abs(fmod(u, 96) - 60) * 0.35);  // sea horizon with an island
            case CITY -> 24 + 13 * hash((long) Math.floor(u / 6), 7);
            case BOUNCY -> 38 - 6 * Math.abs(Math.sin(TAU * 3 * u / p));
            default -> 37 + 3 * Math.sin(TAU * 3 * u / p) + 2 * Math.sin(TAU * 7 * u / p + 2);
        };
    }

    private static int farColor(int theme, double depth) {
        return switch (theme) {
            case JUNGLE -> lerp(0x4E9E78, 0x1F5C43, depth);
            case BEACH -> lerp(0x5EC4E8, 0x1E7FB8, depth);
            case CITY -> lerp(0x3A2C6E, 0x1E1640, depth);
            case BOUNCY -> lerp(0xF7B7E1, 0xE07BC0, depth);
            default -> lerp(0x8ED8A0, 0x4CAF50, depth);
        };
    }

    private static void farLayer(Buf buf, double t, double camX) {
        for (int x = 0; x < W; x++) {
            double u = x / 2.0 + camX * 0.2;
            double[] tb = themeBlend(layerWorld(u, 0.2), 50);
            int a = (int) tb[0], b = (int) tb[1];
            double m = tb[2];
            double top = farHeight(a, u) * (1 - m) + farHeight(b, u) * m;
            for (int y = (int) Math.floor(top * 2); y < 104; y++) {
                double depth = clamp01((y / 2.0 - top) / 14);
                int col = lerp(farColor(a, depth), farColor(b, depth), m);
                double edge = clamp01(y + 1 - top * 2);
                buf.over(x, y, col, edge);
                // City windows, sea glitter.
                int th = m < 0.5 ? a : b;
                long ix = (long) Math.floor(u * 2);                                   // layer coordinate: windows scroll
                if (th == CITY && y > top * 2 + 2 && Math.floorMod(ix, 3L) == 1 && (y % 4 == 1)) {
                    double on = hash(ix * 31 + y, 3);
                    if (on > 0.55) buf.over(x, y, on > 0.9 ? FOUR[(int) (on * 40) % 4] : 0xFFD180, 0.8 * (0.7 + 0.3 * wave(t, 6, on * 9)));
                }
                if (th == BEACH && y < 92 && hash(x + (long) Math.floor(camX * 0.4), y) > 0.97) {
                    buf.add(x, y, 0xFFFFFF, 0.6 * Math.max(0, wave(t, 24, x * 0.7 + y)));
                }
            }
        }
    }

    // ------------------------------------------------------------------ mid layer (factor 0.5, cells of 24)

    private static void midLayer(Buf buf, double t, double camX) {
        double f = 0.5, cell = 24, period = LOOP * f;
        double scroll = camX * f;
        for (int k = (int) Math.floor((scroll - 24) / cell); k <= (scroll + 64 + 24) / cell; k++) {
            double uu = fmod(k * cell, period);
            int th = theme(layerWorld(k * cell + cell / 2, f));
            double sx = (k * cell - scroll) * 2;                                  // hi-res screen x of the cell
            double hsh = hash((long) (uu / cell), 11 + th);
            int haze = SKY[th][1];
            switch (th) {
                case JUNGLE -> jungleTree(buf, sx + 24, hsh, haze, t);
                case BEACH -> { if (hsh > 0.35) palm(buf, sx + 16 + hsh * 16, hsh, haze, t); }
                case CITY -> building(buf, sx + 4, hsh, t);
                case BOUNCY -> lollipop(buf, sx + 24, hsh, t);
                default -> { if (hsh > 0.3) roundTree(buf, sx + 24, hsh, haze, 0.25); }
            }
        }
    }

    private static void jungleTree(Buf buf, double x, double h, int haze, double t) {
        int trunk = lerp(0x3E2723, haze, 0.15), leaf = lerp(0x0F4D2A, haze, 0.12), mid = lerp(0x1B6B3A, haze, 0.12),
                light = lerp(0x3FA45F, haze, 0.1);
        buf.rect(x - 4, 28 + h * 10, x + 4, 100, trunk, 1);
        buf.line(x - 4, 60, x - 14, 100, 3, trunk, 1);                              // buttress roots
        buf.line(x + 4, 62, x + 13, 100, 3, trunk, 1);
        buf.disc(x - 13, 34 + h * 8, 15, leaf, 1);
        buf.disc(x + 13, 30 + h * 8, 16, leaf, 1);
        buf.disc(x, 20 + h * 8, 16, mid, 1);
        for (int i = 0; i < 7; i++) {                                               // leafy texture
            buf.disc(x - 16 + i * 5.5, 22 + h * 8 + 6 * Math.sin(i * 1.7), 3.2, light, 0.7);
        }
        for (int v = 0; v < 3; v++) {                                              // hanging vines swaying
            double vx = x - 12 + v * 11, sway = 2 * wave(t, 3, v * 2.1 + h * 9);
            double len = 18 + 10 * hash(v, (long) (h * 100));
            buf.line(vx, 40 + h * 8, vx + sway, 40 + h * 8 + len, 1.2, lerp(0x2E7D32, haze, 0.2), 0.9);
            buf.disc(vx + sway, 40 + h * 8 + len, 1.6, 0x66BB6A, 0.9);
        }
    }

    private static void palm(Buf buf, double x, double h, int haze, double t) {
        int trunk = lerp(0x8D6E63, haze, 0.2), frond = lerp(0x2E9E5B, haze, 0.2);
        double topX = x + 8, topY = 40 + h * 10;
        for (int i = 0; i <= 10; i++) {
            double u = i / 10.0;
            double px = x + (topX - x) * u * u, py = 96 + (topY - 96) * u;
            buf.disc(px, py, 2.6 - u * 0.8, i % 2 == 0 ? trunk : lerp(trunk, 0, 0.15), 1);
        }
        double sway = 1.5 * wave(t, 3, h * 7);
        for (int i = 0; i < 6; i++) {
            double ang = -Math.PI * (0.05 + i * 0.18) + sway * 0.05;
            double ex = topX + Math.cos(ang) * 24, ey = topY + Math.sin(ang) * 12 + 9;
            buf.line(topX, topY, (topX + ex) / 2, Math.min(topY, ey) - 4, 3, frond, 1);
            buf.line((topX + ex) / 2, Math.min(topY, ey) - 4, ex, ey, 2.2, frond, 1);
        }
        buf.disc(topX - 2, topY + 3, 2, 0x6D4C41, 1);
        buf.disc(topX + 2, topY + 3, 2, 0x5D4037, 1);
    }

    private static void building(Buf buf, double x, double h, double t) {
        double top = 36 + h * 30, right = x + 40;
        int wall = lerp(0x3A2F6B, 0x5B4B9A, h);
        buf.rect(x, top, right, 100, wall, 1);
        buf.rect(x, top, right, top + 2, lerp(wall, 0xFFFFFF, 0.15), 1);
        for (int wy = (int) top + 5; wy < 96; wy += 7) {
            for (int wx = (int) x + 4; wx < right - 4; wx += 7) {
                double lit = hash(wx * 7L + (long) (h * 1000), wy);
                if (lit < 0.45) continue;
                int col = lit > 0.92 ? FOUR[(int) (lit * 97) % 4] : 0xFFD180;
                double flicker = 0.75 + 0.25 * wave(t, 4 + (int) (lit * 5), lit * 20);
                buf.rect(wx, wy, wx + 3, wy + 4, col, flicker);
                buf.glow(wx + 1.5, wy + 2, 3, col, 0.06);
            }
        }
        if (h > 0.5) {                                                             // antenna with a blinking light
            buf.line(x + 20, top, x + 20, top - 10, 1, 0x9E9E9E, 1);
            double blink = Math.max(0, wave(t, 24, h * 10));
            buf.disc(x + 20, top - 11, 1.5, RED, 0.4 + 0.6 * blink);
            buf.glow(x + 20, top - 11, 3, RED, 0.3 * blink);
        }
    }

    private static void lollipop(Buf buf, double x, double h, double t) {
        if (h < 0.5) {                                                             // gumdrop hill
            buf.ellipse(x, 96, 22, 18 + h * 10, lerp(0xFF8AD8, 0xB388FF, h), 1);
            buf.ellipse(x - 6, 86 - h * 8, 6, 3, 0xFFFFFF, 0.35);
            return;
        }
        double topY = 34 + (h - 0.5) * 30;
        buf.rect(x - 1.5, topY, x + 1.5, 100, 0xFFFFFF, 1);
        double spin = TAU * t / DURATION * 2;
        for (int y = (int) (topY - 14); y <= topY + 14; y++) {
            for (int xx = (int) (x - 14); xx <= x + 14; xx++) {
                double dx = xx + 0.5 - x, dy = y + 0.5 - topY;
                double d = Math.hypot(dx, dy);
                if (d > 13.5) continue;
                double swirl = fmod(Math.atan2(dy, dx) / TAU * 4 + d / 6 - spin, 1);
                int col = FOUR[(int) (swirl * 4) % 4];
                buf.over(xx, y, lerp(col, 0xFFFFFF, 0.25), clamp01(13.5 - d));
            }
        }
        buf.disc(x - 5, topY - 5, 3, 0xFFFFFF, 0.5);
    }

    private static void roundTree(Buf buf, double x, double h, int haze, double hazeAmt) {
        buf.rect(x - 2, 70, x + 2, 100, lerp(0x6D4C41, haze, hazeAmt), 1);
        buf.disc(x, 62 - h * 10, 13 + h * 4, lerp(0x2E7D32, haze, hazeAmt), 1);
        buf.disc(x - 4, 57 - h * 10, 7, lerp(0x66BB6A, haze, hazeAmt), 0.8);
    }

    // ------------------------------------------------------------------ near layer (factor 0.8, cells of 16)

    private static void nearLayer(Buf buf, double t, double camX) {
        double f = 0.8, cell = 16, period = LOOP * f;
        double scroll = camX * f;
        for (int k = (int) Math.floor((scroll - 16) / cell); k <= (scroll + 64 + 16) / cell; k++) {
            double uu = fmod(k * cell, period);
            int th = theme(layerWorld(k * cell + cell / 2, f));
            double sx = (k * cell - scroll) * 2 + 16;
            double hsh = hash((long) (uu / cell), 21 + th);
            switch (th) {
                case JUNGLE -> fern(buf, sx, hsh, t);
                case BEACH -> { if (hsh > 0.55) umbrella(buf, sx, hsh); }
                case CITY -> { if (hsh > 0.5) lamp(buf, sx); }
                case BOUNCY -> gumdrop(buf, sx, hsh);
                default -> flowers(buf, sx, hsh, t);
            }
        }
    }

    private static void fern(Buf buf, double x, double h, double t) {
        double sway = wave(t, 4, h * 9) * 1.5;
        for (int i = -3; i <= 3; i++) {
            double ang = -Math.PI / 2 + i * 0.32;
            buf.line(x, 104, x + Math.cos(ang) * 14 + sway, 104 + Math.sin(ang) * 12, 2.2, i % 2 == 0 ? 0x2E7D32 : 0x388E3C, 1);
        }
        if (h > 0.6) {                                                             // little mushroom
            buf.rect(x + 9, 98, x + 11, 104, 0xFFF3E0, 1);
            buf.ellipse(x + 10, 98, 4, 2.5, RED, 1);
            buf.disc(x + 9, 97, 0.8, 0xFFFFFF, 1);
        }
    }

    private static void umbrella(Buf buf, double x, double h) {
        buf.line(x, 76, x + 2, 104, 1.2, 0xEEEEEE, 1);
        int c1 = FOUR[(int) (h * 13) % 4], c2 = 0xFFFFFF;
        for (int y = 66; y <= 78; y++) {
            for (int xx = (int) x - 15; xx <= x + 15; xx++) {
                double dx = xx + 0.5 - x, dy = y + 0.5 - 78;
                if (dy > 0 || dx * dx / 225 + dy * dy / 144 > 1) continue;
                int stripe = (int) Math.floor((Math.atan2(dy, dx) + Math.PI) / (Math.PI / 6));
                buf.over(xx, y, stripe % 2 == 0 ? c1 : c2, 1);
            }
        }
    }

    private static void lamp(Buf buf, double x) {
        buf.rect(x - 1, 62, x + 1, 104, 0x455A64, 1);
        buf.rect(x - 4, 60, x + 4, 63, 0x37474F, 1);
        buf.disc(x, 64, 2, 0xFFF59D, 1);
        buf.glow(x, 66, 9, 0xFFE082, 0.35);
        for (int y = 66; y < 104; y++) {                                           // light cone
            double half = (y - 64) * 0.35;
            for (int xx = (int) (x - half); xx <= x + half; xx++) buf.add(xx, y, 0xFFE082, 0.05);
        }
    }

    private static void gumdrop(Buf buf, double x, double h) {
        int col = lerp(FOUR[(int) (h * 31) % 4], 0xFFFFFF, 0.2);
        double r = 5 + h * 4;
        buf.ellipse(x, 104 - r * 0.6, r, r * 0.9, col, 1);
        buf.disc(x - r * 0.35, 104 - r * 1.1, r * 0.25, 0xFFFFFF, 0.6);
        if (h > 0.7) {                                                             // candy cane
            buf.line(x + 10, 104, x + 10, 84, 2.5, 0xFFFFFF, 1);
            for (int y = 86; y < 104; y += 5) buf.line(x + 9, y, x + 11, y + 2, 2.5, RED, 1);
            buf.line(x + 10, 84, x + 14, 81, 2.5, RED, 1);
        }
    }

    private static void flowers(Buf buf, double x, double h, double t) {
        double sway = wave(t, 5, h * 11);
        for (int i = 0; i < 3; i++) {
            double fx = x + (i - 1) * 6 + h * 4, top = 92 - hash(i, (long) (h * 99)) * 8;
            buf.line(fx, 104, fx + sway, top, 1, 0x388E3C, 1);
            int col = FOUR[(int) (h * 7 + i) % 4];
            buf.disc(fx + sway, top, 2, col, 1);
            buf.disc(fx + sway, top, 0.8, YELLOW, 1);
        }
        for (int i = 0; i < 4; i++) buf.line(x - 6 + i * 4, 104, x - 7 + i * 4 + sway, 97, 1, 0x66BB6A, 1);
    }

    // ------------------------------------------------------------------ ground (factor 1)

    private static int groundColor(int theme, double wx, int row, double t) {
        // row: 0 = top of the ground, in hi-res pixels (0..23)
        switch (theme) {
            case JUNGLE -> {
                if (row < 4) return row < 2 && hash((long) (wx * 2), 1) > 0.6 ? 0x66BB6A : 0x43A047;
                double stone = hash((long) Math.floor(wx / 3), row / 3);
                return stone > 0.93 ? 0x6D4C41 : (row % 7 == 3 && stone > 0.6 ? 0x3E2723 : 0x4E342E);
            }
            case BEACH -> {
                double ripple = Math.sin(wx * 1.3 + row * 0.9) * 0.5 + 0.5;
                int sand = lerp(0xF2D492, 0xE8C377, ripple * 0.5 + row / 48.0);
                if (row < 2) sand = lerp(sand, 0xFFF3C4, 0.5);
                if (hash((long) Math.floor(wx * 2), row) > 0.985) sand = 0xFFFFFF;            // shells
                return sand;
            }
            case CITY -> {
                if (row < 2) return 0xB0BEC5;                                                  // curb
                if (row < 8) return fmod(wx, 8) < 0.5 ? 0x546E7A : 0x78909C;                   // sidewalk slabs
                if (row >= 15 && row < 17 && fmod(wx, 24) < 12) return 0xFFD54F;               // lane dashes
                return 0x37474F;
            }
            case BOUNCY -> {
                double stripe = fmod(wx + row * 0.5, 12) / 12;
                int col = lerp(0xFF80C0, lerp(FOUR[(int) (fmod(wx / 12, 4))], 0xFFFFFF, 0.45), stripe < 0.5 ? 0.6 : 0);
                if (row < 2) col = lerp(col, 0xFFFFFF, 0.55);                                  // glossy top
                return col;
            }
            default -> {
                if (row < 4) return row < 2 && hash((long) (wx * 2), 9) > 0.5 ? 0x81C784 : 0x66BB6A;
                return row % 6 == 5 && hash((long) Math.floor(wx / 2), row) > 0.5 ? 0x5D4037 : 0x795548;
            }
        }
    }

    private static void ground(Buf buf, double t, double camX) {
        for (int x = 0; x < W; x++) {
            double wx = camX + (x + 0.5) / 2;
            double[] tb = themeBlend(wx, 10);
            int a = (int) tb[0], b = (int) tb[1];
            double m = tb[2];
            double bounce = 0;
            if ((a == BOUNCY && m < 0.5) || (b == BOUNCY && m >= 0.5)) bounce = 0.8 * wave(t, 12, wx * 0.3);
            int top = (int) Math.round(GROUND * 2 + bounce);
            for (int y = top; y < W; y++) {
                int row = y - top;
                // Organic dithered border between regions instead of a fade.
                boolean useB = m > hash((long) Math.floor(wx * 2), y);
                buf.over(x, y, groundColor(useB ? b : a, wx, row, t), 1);
            }
        }
    }

    // ------------------------------------------------------------------ things

    private static void things(Buf buf, double t, double camX, double devWx) {
        for (Thing th : THINGS) {
            double r = rel(th.x(), devWx);
            double sx = (DEV_X + r) * 2;                                            // hi-res screen x
            if (sx < -30 || sx > W + 30) continue;
            double gy = GROUND * 2;
            switch (th.kind()) {
                case BUG -> bug(buf, sx, gy, th.theme(), r < 0, t);
                case COIN -> {
                    if (r < 0) break;                                               // collected
                    Arc a = arcAt(th.x());
                    double apex = a == null ? 12 : heightAt(th.x());
                    coin(buf, sx, gy - (apex + 18) * 2, t);
                }
                case LOG -> {
                    buf.rect(sx - 14, gy - 12, sx + 14, gy, 0x6D4C41, 1);
                    buf.rect(sx - 14, gy - 12, sx + 14, gy - 10, 0x8D6E63, 1);
                    buf.ellipse(sx + 14, gy - 6, 3, 6, 0xA1887F, 1);
                    buf.ellipse(sx + 14, gy - 6, 1.5, 3, 0x795548, 1);
                    buf.disc(sx - 6, gy - 12, 2, 0x66BB6A, 1);                      // moss
                }
                case CASTLE -> {
                    int sand = 0xE6C27A;
                    buf.rect(sx - 12, gy - 10, sx + 12, gy, sand, 1);
                    buf.rect(sx - 12, gy - 18, sx - 5, gy - 10, sand, 1);
                    buf.rect(sx + 5, gy - 18, sx + 12, gy - 10, sand, 1);
                    for (int c = 0; c < 2; c++) {
                        double cx = c == 0 ? sx - 12 : sx + 5;
                        buf.rect(cx, gy - 20, cx + 2, gy - 18, sand, 1);
                        buf.rect(cx + 5, gy - 20, cx + 7, gy - 18, sand, 1);
                    }
                    buf.rect(sx - 2, gy - 6, sx + 2, gy, 0xB08850, 1);
                    buf.line(sx + 8, gy - 20, sx + 8, gy - 28, 1, 0x795548, 1);
                    buf.rect(sx + 8, gy - 28, sx + 13, gy - 25 + wave(t, 12, 0), RED, 1);
                }
                case CONE -> {
                    for (int y = 0; y < 20; y++) {
                        double half = 2 + y * 0.35;
                        boolean white = y > 6 && y < 10 || y > 13 && y < 16;
                        buf.rect(sx - half, gy - 20 + y, sx + half, gy - 19 + y, white ? 0xFFFFFF : 0xFF6D00, 1);
                    }
                    buf.rect(sx - 10, gy - 2, sx + 10, gy, 0xE65100, 1);
                }
                case HYDRANT -> {
                    buf.rect(sx - 6, gy - 18, sx + 6, gy, RED, 1);
                    buf.ellipse(sx, gy - 18, 6, 3, 0xC62828, 1);
                    buf.rect(sx - 10, gy - 12, sx + 10, gy - 8, 0xC62828, 1);
                    buf.rect(sx - 3, gy - 18, sx - 1, gy, 0xEF5350, 1);
                }
                case ROCK -> {
                    buf.ellipse(sx, gy - 7, 13, 9, 0x78909C, 1);
                    buf.ellipse(sx - 4, gy - 11, 5, 3, 0xB0BEC5, 0.8);
                }
                case TRAMPOLINE -> {
                    double squash = r < 0 && r > -14 ? 3 * Math.exp(r / 4) : 0;    // dips right after the launch
                    buf.line(sx - 12, gy, sx - 9, gy - 8, 2, 0x455A64, 1);
                    buf.line(sx + 12, gy, sx + 9, gy - 8, 2, 0x455A64, 1);
                    buf.ellipse(sx, gy - 8 + squash, 14, 3, BLUE, 1);
                    buf.ellipse(sx, gy - 9 + squash, 12, 1.5, 0x8AB4F8, 1);
                }
                default -> { }
            }
        }
    }

    private static void bug(Buf buf, double sx, double gy, int theme, boolean squashed, double t) {
        int shell = FOUR[(theme + 1) % 4];
        if (squashed) {
            buf.ellipse(sx, gy - 2, 10, 2.5, lerp(shell, 0, 0.2), 1);
            buf.disc(sx - 3, gy - 3, 1.2, 0xFFFFFF, 1);
            buf.disc(sx + 3, gy - 3, 1.2, 0xFFFFFF, 1);
            return;
        }
        double step = wave(t, 48, sx * 0.1);
        for (int l = -1; l <= 1; l++) buf.line(sx + l * 5, gy - 3, sx + l * 5 + 2 * step * (l == 0 ? -1 : 1), gy, 1.2, 0x37474F, 1);
        buf.ellipse(sx, gy - 6, 9, 6, shell, 1);
        buf.ellipse(sx - 2, gy - 9, 4, 2, lerp(shell, 0xFFFFFF, 0.5), 0.8);
        buf.disc(sx + 3, gy - 6, 1.6, lerp(shell, 0, 0.45), 1);
        buf.disc(sx - 3, gy - 4, 1.4, lerp(shell, 0, 0.45), 1);
        buf.disc(sx - 8, gy - 6, 3.5, 0x37474F, 1);                                  // head (facing the runner)
        buf.disc(sx - 9, gy - 7, 1.4, 0xFFFFFF, 1);
        buf.disc(sx - 9.5, gy - 7, 0.7, 0x000000, 1);
        buf.line(sx - 9, gy - 9, sx - 12, gy - 13, 0.8, 0x37474F, 1);
        if (theme == BEACH) {                                                       // crab claws
            buf.disc(sx - 13, gy - 9 + step, 2.5, RED, 1);
            buf.disc(sx + 11, gy - 9 - step, 2.5, RED, 1);
        }
    }

    private static void coin(Buf buf, double cx, double cy, double t) {
        double spin = Math.cos(TAU * 6 * t / DURATION);
        double w = Math.max(0.25, Math.abs(spin));
        buf.glow(cx, cy, 6, 0xFFD54F, 0.35);
        buf.ellipse(cx, cy, 7 * w + 0.5, 7, 0xF9A825, 1);
        buf.ellipse(cx, cy, 5.5 * w, 5.5, 0xFFF8E1, 1);
        // The G in Google colors, squashed with the spin.
        for (int y = -4; y <= 4; y++) {
            for (int x = -4; x <= 4; x++) {
                double gx = x / Math.max(0.3, w), gy = y;
                double d = Math.hypot(gx, gy);
                double ang = Math.atan2(gy, gx);
                boolean ring = d > 2.2 && d < 3.9 && !(ang > -0.6 && ang < 0.25);
                boolean bar = gy > -0.6 && gy < 0.9 && gx > 0 && gx < 3.9;
                if (!ring && !bar) continue;
                int col = bar || (ang > -0.6 && ang < 0.8) ? BLUE : ang >= 0.8 && ang < 2.3 ? GREEN : ang >= 2.3 || ang < -2.4 ? YELLOW : RED;
                buf.over((int) Math.round(cx + x), (int) Math.round(cy + y), col, 1);
            }
        }
    }

    // ------------------------------------------------------------------ the runner

    private static void runner(Buf buf, double devWx) {
        double h = heightAt(devWx);
        Arc arc = arcAt(devWx);
        Pose pose;
        if (arc != null) {
            pose = POSES.get(Math.min(4, POSES.size() - 1));                          // jump
        } else {
            Arc prev = null;
            for (Arc a : ARCS) if (a.x1() <= devWx && devWx - a.x1() < 5) prev = a;
            int run = (int) Math.floorMod((long) Math.floor(devWx / 6), 4L);
            pose = prev != null && POSES.size() > 5 ? POSES.get(5) : POSES.get(run); // landing, else run cycle
        }
        double feet = (GROUND - h) * 2;
        // Soft contact shadow that shrinks as he jumps.
        double k = clamp01(1 - h / 30);
        buf.ellipse(DEV_X * 2, GROUND * 2 + 1, 9 * k + 2, 1.6 * k + 0.4, 0x000000, 0.25 * k);
        drawPose(buf, pose, DEV_X * 2, feet + 1);
    }

    // ------------------------------------------------------------------ effects

    private static void effects(Buf buf, double t, double camX, double devWx) {
        // Landing dust, stomp poofs and coin sparkles (all keyed to the runner's position, so they loop).
        for (Arc a : ARCS) {
            double r = devWx - a.x1();
            r = fmod(r + LOOP / 2, LOOP) - LOOP / 2;
            if (a.ground1() && r >= 0 && r < 16) {
                double k = 1 - r / 16;
                int dust = switch (theme(a.x1())) { case BEACH -> 0xF2D492; case CITY -> 0xB0BEC5; case BOUNCY -> 0xFFB3E0; default -> 0xD7CCC8; };
                for (int s = -1; s <= 1; s += 2) {
                    buf.disc(DEV_X * 2 + s * (4 + r * 1.2), GROUND * 2 - 2 - r * 0.3, 2.5 + r * 0.15, dust, 0.55 * k);
                }
            }
        }
        for (Thing th : THINGS) {
            double r = -rel(th.x(), devWx);                                         // how far past it we are
            if (r < 0 || r > 22) continue;
            double sx = (DEV_X - r) * 2, k = 1 - r / 22;
            if (th.kind() == BUG) {                                                  // colorful smoke poof
                double gy = GROUND * 2 - 6;
                for (int y = (int) gy - 14; y <= gy + 6; y++) {
                    for (int x = (int) sx - 16; x <= sx + 16; x++) {
                        double d = Math.hypot(x + 0.5 - sx, y + 0.5 - gy);
                        double ring = Math.exp(-Math.pow((d - (3 + r * 0.6)) / 3.5, 2));
                        double n = Noise.fbm(x * 0.15, y * 0.15, th.x() * 0.1, 3);
                        buf.add(x, y, FOUR[(int) Math.floorMod((long) Math.floor(n * 4 + Math.atan2(y - gy, x - sx) * 0.6), 4L)],
                                ring * k * 0.5 * smoothstep(-0.3, 0.4, n));
                    }
                }
            } else if (th.kind() == COIN) {                                          // sparkle burst
                double cy = GROUND * 2 - (heightAt(th.x()) + 18) * 2;
                for (int i = 0; i < 8; i++) {
                    double ang = TAU * i / 8, d = 3 + r * 1.2;
                    buf.disc(DEV_X * 2 + 6 + Math.cos(ang) * d, cy + Math.sin(ang) * d, 1.3 * k + 0.3, FOUR[i % 4], k);
                }
            }
        }
        // Theme ambience, weighted by how much of that theme is on screen.
        double[] tb = themeBlend(camX + 32, 70);
        for (int s = 0; s < 2; s++) {
            int th = (int) tb[s];
            double w = s == 0 ? 1 - tb[2] : tb[2];
            if (w <= 0.01 || (s == 1 && tb[0] == tb[1])) continue;
            for (int i = 0; i < 9; i++) {
                double ph = hash(i, th + 40);
                switch (th) {
                    case JUNGLE -> {                                                 // fireflies
                        double x = fmod(ph * 128 + 12 * wave(t, 2, i), 128), y = 50 + 30 * hash(i, 41) + 6 * wave(t, 3, i * 2);
                        buf.glow(x, y, 2.2, 0xEEFF41, w * 0.6 * Math.max(0, wave(t, 10 + i, i)));
                    }
                    case BOUNCY -> {                                                 // rising bubbles
                        double y = fmod(110 - (t / DURATION * 6 + ph) * 128, 128), x = ph * 128 + 3 * wave(t, 8, i);
                        for (int a = 0; a < 24; a++) {
                            double ang = TAU * a / 24;
                            buf.add((int) (x + Math.cos(ang) * 3.5), (int) (y + Math.sin(ang) * 3.5), 0xFFFFFF, w * 0.35);
                        }
                        buf.disc(x - 1.2, y - 1.2, 0.8, 0xFFFFFF, w * 0.7);
                    }
                    case GRASS -> {                                                  // butterflies
                        if (i > 3) break;
                        double x = fmod(ph * 128 + t * 128 / DURATION, 128), y = 50 + 20 * hash(i, 43) + 5 * wave(t, 6, i);
                        double flap = Math.abs(wave(t, 120, i));
                        buf.ellipse(x - 1.8, y, 1.8 * flap + 0.4, 2, FOUR[i % 4], w);
                        buf.ellipse(x + 1.8, y, 1.8 * flap + 0.4, 2, FOUR[i % 4], w);
                    }
                    default -> { }
                }
            }
        }
    }

    /** The smiling Google Cloud from the original dev-runner, floating along like Lakitu. */
    private static void companion(Buf buf, double t) {
        double cx = 86 + 8 * wave(t, 2, 0), cy = 16 + 2.5 * wave(t, 4, 1);
        double[][] puffs = {{0, 2, 9}, {-9, 4, 6.5}, {9, 3, 7}, {-4, -4, 7}, {5, -5, 6}};
        for (int y = (int) cy - 14; y <= cy + 12; y++) {
            for (int x = (int) cx - 18; x <= cx + 18; x++) {
                double u = x + 0.5 - cx, v = y + 0.5 - cy;
                double inside = -1;
                for (double[] p : puffs) inside = Math.max(inside, p[2] - Math.hypot(u - p[0], v - p[1]));
                if (inside < 0 || v > 10) continue;
                int col;
                if (inside < 1.2) {
                    double a = Math.atan2(v, u);
                    col = v > 6 ? BLUE : a < -2.0 || a > 2.6 ? YELLOW : a < -1.0 ? RED : GREEN;
                } else {
                    col = lerp(0xE3E8F5, 0xFFFFFF, clamp01(0.6 - v / 14));
                }
                buf.over(x, y, col, clamp01(inside + 0.5));
            }
        }
        boolean blink = fmod(t, 4.8) > 4.6;
        for (int s = -1; s <= 1; s += 2) {
            if (blink) buf.line(cx + s * 3.5 - 1.2, cy, cx + s * 3.5 + 1.2, cy, 0.8, 0x202124, 1);
            else buf.disc(cx + s * 3.5, cy, 1.3, 0x202124, 1);
            buf.disc(cx + s * 6.5, cy + 2.5, 1.6, 0xF6AEA9, 0.8);
        }
        buf.line(cx - 1.8, cy + 3, cx, cy + 4, 0.8, 0x202124, 1);
        buf.line(cx, cy + 4, cx + 1.8, cy + 3, 0.8, 0x202124, 1);
    }

    // ------------------------------------------------------------------ foreground (factor 1.4)

    private static void foreground(Buf buf, double t, double camX) {
        double f = 1.4, cell = 96, period = LOOP * f;
        double scroll = camX * f;
        for (int k = (int) Math.floor((scroll - 40) / cell); k <= (scroll + 64 + 40) / cell; k++) {
            double uu = fmod(k * cell, period);
            double hsh = hash((long) (uu / cell), 77);
            if (hsh < 0.45) continue;
            int th = theme(layerWorld(k * cell + cell / 2, f));
            double sx = (k * cell - scroll) * 2 + 40;
            int dark = lerp(SKY[th][0], 0x000000, 0.55);
            switch (th) {
                case JUNGLE -> { for (int i = -2; i <= 2; i++) buf.line(sx, 128, sx + i * 9, 104 + Math.abs(i) * 4, 4, dark, 0.9); }
                case BEACH -> buf.ellipse(sx, 128, 16, 8, lerp(0xE8C377, 0, 0.35), 0.95);
                case CITY -> buf.rect(sx - 3, 90, sx + 3, 128, dark, 0.95);
                case BOUNCY -> buf.disc(sx, 124, 9, lerp(FOUR[(int) (hsh * 9) % 4], 0x000000, 0.35), 0.9);
                default -> { for (int i = -3; i <= 3; i++) buf.line(sx + i * 3, 128, sx + i * 4, 108 + Math.abs(i) * 3, 2, dark, 0.9); }
            }
        }
    }
}
